/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const RatingCategory = IDL.Record({
  'service' : IDL.Nat,
  'trust' : IDL.Nat,
  'info' : IDL.Nat,
  'followUp' : IDL.Nat,
  'speed' : IDL.Nat,
  'politeness' : IDL.Nat,
});
export const UserId = IDL.Principal;
export const Agent = IDL.Record({
  'id' : IDL.Nat,
  'portfolio' : IDL.Vec(IDL.Text),
  'serviceArea' : IDL.Text,
  'ratingCategories' : RatingCategory,
  'listedHomes' : IDL.Vec(IDL.Nat),
  'verified' : IDL.Bool,
  'userId' : UserId,
  'managedProjects' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'agentCode' : IDL.Text,
  'experience' : IDL.Nat,
  'customerCount' : IDL.Nat,
  'rating' : IDL.Float64,
  'photo' : IDL.Opt(IDL.Text),
  'reviewCount' : IDL.Nat,
});
export const HouseStatus = IDL.Variant({
  'underConstruction' : IDL.Null,
  'readyToMove' : IDL.Null,
});
export const House = IDL.Record({
  'id' : IDL.Nat,
  'status' : HouseStatus,
  'bedrooms' : IDL.Nat,
  'video' : IDL.Opt(IDL.Text),
  'floorPlan' : IDL.Opt(IDL.Text),
  'projectId' : IDL.Nat,
  'usableArea' : IDL.Nat,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'houseType' : IDL.Text,
  'parking' : IDL.Nat,
  'gallery' : IDL.Vec(IDL.Text),
});
export const Timestamp = IDL.Int;
export const Location = IDL.Record({
  'province' : IDL.Text,
  'district' : IDL.Text,
  'subDistrict' : IDL.Text,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'likeCount' : IDL.Nat,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'agentId' : IDL.Opt(IDL.Nat),
  'interestedCount' : IDL.Nat,
  'shareCount' : IDL.Nat,
  'projectId' : IDL.Opt(IDL.Nat),
  'commentCount' : IDL.Nat,
  'image' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Nat),
  'saveCount' : IDL.Nat,
  'location' : IDL.Opt(Location),
});
export const UnitStatus = IDL.Variant({
  'sold' : IDL.Null,
  'reserved' : IDL.Null,
  'available' : IDL.Null,
});
export const ProjectStatus = IDL.Variant({
  'new' : IDL.Null,
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const VerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'none' : IDL.Null,
  'official' : IDL.Null,
});
export const Coordinates = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'promotions' : IDL.Vec(IDL.Text),
  'startingPrice' : IDL.Nat,
  'unitStatus' : UnitStatus,
  'reviewRating' : IDL.Float64,
  'video' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'unitCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'houseTypes' : IDL.Vec(IDL.Text),
  'projectStatus' : ProjectStatus,
  'location' : Location,
  'verificationStatus' : VerificationStatus,
  'coordinates' : Coordinates,
  'images' : IDL.Vec(IDL.Text),
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'categories' : RatingCategory,
  'createdAt' : Timestamp,
  'agentId' : IDL.Nat,
  'reviewerId' : UserId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'reported' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : AppointmentStatus,
  'visitors' : IDL.Nat,
  'userId' : UserId,
  'date' : Timestamp,
  'name' : IDL.Text,
  'time' : Timestamp,
  'agentId' : IDL.Opt(IDL.Nat),
  'projectId' : IDL.Nat,
  'phone' : IDL.Text,
  'houseType' : IDL.Opt(IDL.Text),
  'houseId' : IDL.Opt(IDL.Nat),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AdminMetrics = IDL.Record({
  'members' : IDL.Nat,
  'projects' : IDL.Nat,
  'agents' : IDL.Nat,
  'leads' : IDL.Nat,
  'liveViewers' : IDL.Nat,
  'appointments' : IDL.Nat,
  'conversions' : IDL.Nat,
  'posts' : IDL.Nat,
  'houses' : IDL.Nat,
  'customers' : IDL.Nat,
});
export const Favorite = IDL.Record({
  'projects' : IDL.Vec(IDL.Nat),
  'userId' : UserId,
  'agents' : IDL.Vec(IDL.Nat),
  'savedPosts' : IDL.Vec(IDL.Nat),
  'houseTypes' : IDL.Vec(IDL.Text),
  'houses' : IDL.Vec(IDL.Nat),
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'message' : IDL.Text,
});
export const ProjectFilter = IDL.Record({
  'province' : IDL.Opt(IDL.Text),
  'newProject' : IDL.Opt(IDL.Bool),
  'bedrooms' : IDL.Opt(IDL.Nat),
  'name' : IDL.Opt(IDL.Text),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'district' : IDL.Opt(IDL.Text),
  'promotion' : IDL.Opt(IDL.Bool),
  'usableArea' : IDL.Opt(IDL.Nat),
  'minPrice' : IDL.Opt(IDL.Nat),
  'houseType' : IDL.Opt(IDL.Text),
  'readyToMove' : IDL.Opt(IDL.Bool),
  'location' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addAgent' : IDL.Func([Agent], [IDL.Nat], []),
  'addFavoriteAgent' : IDL.Func([IDL.Nat], [], []),
  'addFavoriteHouse' : IDL.Func([IDL.Nat], [], []),
  'addFavoriteHouseType' : IDL.Func([IDL.Text], [], []),
  'addFavoriteProject' : IDL.Func([IDL.Nat], [], []),
  'addHouse' : IDL.Func([House], [IDL.Nat], []),
  'addPost' : IDL.Func([Post], [IDL.Nat], []),
  'addProject' : IDL.Func([Project], [IDL.Nat], []),
  'addReview' : IDL.Func([Review], [IDL.Nat], []),
  'addSavedPost' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func([Appointment], [IDL.Nat], []),
  'cancelAppointment' : IDL.Func([IDL.Nat], [], []),
  'commentPost' : IDL.Func([IDL.Nat], [], []),
  'confirmAppointment' : IDL.Func([IDL.Nat], [], []),
  'deleteAgent' : IDL.Func([IDL.Nat], [], []),
  'deleteHouse' : IDL.Func([IDL.Nat], [], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAdminMetrics' : IDL.Func([], [AdminMetrics], ['query']),
  'getAgent' : IDL.Func([IDL.Nat], [IDL.Opt(Agent)], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getAppointment' : IDL.Func([IDL.Nat], [IDL.Opt(Appointment)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func([], [Favorite], ['query']),
  'getHouse' : IDL.Func([IDL.Nat], [IDL.Opt(House)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'listAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
  'listAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'listHouses' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(House)], ['query']),
  'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'listProjects' : IDL.Func([ProjectFilter], [IDL.Vec(Project)], ['query']),
  'listReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'removeFavoriteAgent' : IDL.Func([IDL.Nat], [], []),
  'removeFavoriteHouse' : IDL.Func([IDL.Nat], [], []),
  'removeFavoriteHouseType' : IDL.Func([IDL.Text], [], []),
  'removeFavoriteProject' : IDL.Func([IDL.Nat], [], []),
  'removeSavedPost' : IDL.Func([IDL.Nat], [], []),
  'reportReview' : IDL.Func([IDL.Nat], [], []),
  'savePost' : IDL.Func([IDL.Nat], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sharePost' : IDL.Func([IDL.Nat], [], []),
  'smartSearch' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
  'updateAgent' : IDL.Func([Agent], [], []),
  'updateHouse' : IDL.Func([House], [], []),
  'updateProject' : IDL.Func([Project], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const RatingCategory = IDL.Record({
    'service' : IDL.Nat,
    'trust' : IDL.Nat,
    'info' : IDL.Nat,
    'followUp' : IDL.Nat,
    'speed' : IDL.Nat,
    'politeness' : IDL.Nat,
  });
  const UserId = IDL.Principal;
  const Agent = IDL.Record({
    'id' : IDL.Nat,
    'portfolio' : IDL.Vec(IDL.Text),
    'serviceArea' : IDL.Text,
    'ratingCategories' : RatingCategory,
    'listedHomes' : IDL.Vec(IDL.Nat),
    'verified' : IDL.Bool,
    'userId' : UserId,
    'managedProjects' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'agentCode' : IDL.Text,
    'experience' : IDL.Nat,
    'customerCount' : IDL.Nat,
    'rating' : IDL.Float64,
    'photo' : IDL.Opt(IDL.Text),
    'reviewCount' : IDL.Nat,
  });
  const HouseStatus = IDL.Variant({
    'underConstruction' : IDL.Null,
    'readyToMove' : IDL.Null,
  });
  const House = IDL.Record({
    'id' : IDL.Nat,
    'status' : HouseStatus,
    'bedrooms' : IDL.Nat,
    'video' : IDL.Opt(IDL.Text),
    'floorPlan' : IDL.Opt(IDL.Text),
    'projectId' : IDL.Nat,
    'usableArea' : IDL.Nat,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'houseType' : IDL.Text,
    'parking' : IDL.Nat,
    'gallery' : IDL.Vec(IDL.Text),
  });
  const Timestamp = IDL.Int;
  const Location = IDL.Record({
    'province' : IDL.Text,
    'district' : IDL.Text,
    'subDistrict' : IDL.Text,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'likeCount' : IDL.Nat,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'agentId' : IDL.Opt(IDL.Nat),
    'interestedCount' : IDL.Nat,
    'shareCount' : IDL.Nat,
    'projectId' : IDL.Opt(IDL.Nat),
    'commentCount' : IDL.Nat,
    'image' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Nat),
    'saveCount' : IDL.Nat,
    'location' : IDL.Opt(Location),
  });
  const UnitStatus = IDL.Variant({
    'sold' : IDL.Null,
    'reserved' : IDL.Null,
    'available' : IDL.Null,
  });
  const ProjectStatus = IDL.Variant({
    'new' : IDL.Null,
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const VerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'none' : IDL.Null,
    'official' : IDL.Null,
  });
  const Coordinates = IDL.Record({ 'lat' : IDL.Float64, 'lng' : IDL.Float64 });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'promotions' : IDL.Vec(IDL.Text),
    'startingPrice' : IDL.Nat,
    'unitStatus' : UnitStatus,
    'reviewRating' : IDL.Float64,
    'video' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'unitCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'houseTypes' : IDL.Vec(IDL.Text),
    'projectStatus' : ProjectStatus,
    'location' : Location,
    'verificationStatus' : VerificationStatus,
    'coordinates' : Coordinates,
    'images' : IDL.Vec(IDL.Text),
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'categories' : RatingCategory,
    'createdAt' : Timestamp,
    'agentId' : IDL.Nat,
    'reviewerId' : UserId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'reported' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : AppointmentStatus,
    'visitors' : IDL.Nat,
    'userId' : UserId,
    'date' : Timestamp,
    'name' : IDL.Text,
    'time' : Timestamp,
    'agentId' : IDL.Opt(IDL.Nat),
    'projectId' : IDL.Nat,
    'phone' : IDL.Text,
    'houseType' : IDL.Opt(IDL.Text),
    'houseId' : IDL.Opt(IDL.Nat),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AdminMetrics = IDL.Record({
    'members' : IDL.Nat,
    'projects' : IDL.Nat,
    'agents' : IDL.Nat,
    'leads' : IDL.Nat,
    'liveViewers' : IDL.Nat,
    'appointments' : IDL.Nat,
    'conversions' : IDL.Nat,
    'posts' : IDL.Nat,
    'houses' : IDL.Nat,
    'customers' : IDL.Nat,
  });
  const Favorite = IDL.Record({
    'projects' : IDL.Vec(IDL.Nat),
    'userId' : UserId,
    'agents' : IDL.Vec(IDL.Nat),
    'savedPosts' : IDL.Vec(IDL.Nat),
    'houseTypes' : IDL.Vec(IDL.Text),
    'houses' : IDL.Vec(IDL.Nat),
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'message' : IDL.Text,
  });
  const ProjectFilter = IDL.Record({
    'province' : IDL.Opt(IDL.Text),
    'newProject' : IDL.Opt(IDL.Bool),
    'bedrooms' : IDL.Opt(IDL.Nat),
    'name' : IDL.Opt(IDL.Text),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'district' : IDL.Opt(IDL.Text),
    'promotion' : IDL.Opt(IDL.Bool),
    'usableArea' : IDL.Opt(IDL.Nat),
    'minPrice' : IDL.Opt(IDL.Nat),
    'houseType' : IDL.Opt(IDL.Text),
    'readyToMove' : IDL.Opt(IDL.Bool),
    'location' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addAgent' : IDL.Func([Agent], [IDL.Nat], []),
    'addFavoriteAgent' : IDL.Func([IDL.Nat], [], []),
    'addFavoriteHouse' : IDL.Func([IDL.Nat], [], []),
    'addFavoriteHouseType' : IDL.Func([IDL.Text], [], []),
    'addFavoriteProject' : IDL.Func([IDL.Nat], [], []),
    'addHouse' : IDL.Func([House], [IDL.Nat], []),
    'addPost' : IDL.Func([Post], [IDL.Nat], []),
    'addProject' : IDL.Func([Project], [IDL.Nat], []),
    'addReview' : IDL.Func([Review], [IDL.Nat], []),
    'addSavedPost' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func([Appointment], [IDL.Nat], []),
    'cancelAppointment' : IDL.Func([IDL.Nat], [], []),
    'commentPost' : IDL.Func([IDL.Nat], [], []),
    'confirmAppointment' : IDL.Func([IDL.Nat], [], []),
    'deleteAgent' : IDL.Func([IDL.Nat], [], []),
    'deleteHouse' : IDL.Func([IDL.Nat], [], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAdminMetrics' : IDL.Func([], [AdminMetrics], ['query']),
    'getAgent' : IDL.Func([IDL.Nat], [IDL.Opt(Agent)], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getAppointment' : IDL.Func([IDL.Nat], [IDL.Opt(Appointment)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func([], [Favorite], ['query']),
    'getHouse' : IDL.Func([IDL.Nat], [IDL.Opt(House)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'listAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
    'listAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'listHouses' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(House)], ['query']),
    'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'listProjects' : IDL.Func([ProjectFilter], [IDL.Vec(Project)], ['query']),
    'listReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'removeFavoriteAgent' : IDL.Func([IDL.Nat], [], []),
    'removeFavoriteHouse' : IDL.Func([IDL.Nat], [], []),
    'removeFavoriteHouseType' : IDL.Func([IDL.Text], [], []),
    'removeFavoriteProject' : IDL.Func([IDL.Nat], [], []),
    'removeSavedPost' : IDL.Func([IDL.Nat], [], []),
    'reportReview' : IDL.Func([IDL.Nat], [], []),
    'savePost' : IDL.Func([IDL.Nat], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sharePost' : IDL.Func([IDL.Nat], [], []),
    'smartSearch' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
    'updateAgent' : IDL.Func([Agent], [], []),
    'updateHouse' : IDL.Func([House], [], []),
    'updateProject' : IDL.Func([Project], [], []),
  });
};

export const init = ({ IDL }) => { return []; };