/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminMetrics {
  'members' : bigint,
  'projects' : bigint,
  'agents' : bigint,
  'leads' : bigint,
  'liveViewers' : bigint,
  'appointments' : bigint,
  'conversions' : bigint,
  'posts' : bigint,
  'houses' : bigint,
  'customers' : bigint,
}
export interface Agent {
  'id' : bigint,
  'portfolio' : Array<string>,
  'serviceArea' : string,
  'ratingCategories' : RatingCategory,
  'listedHomes' : Array<bigint>,
  'verified' : boolean,
  'userId' : UserId,
  'managedProjects' : Array<bigint>,
  'name' : string,
  'agentCode' : string,
  'experience' : bigint,
  'customerCount' : bigint,
  'rating' : number,
  'photo' : [] | [string],
  'reviewCount' : bigint,
}
export interface Appointment {
  'id' : bigint,
  'status' : AppointmentStatus,
  'visitors' : bigint,
  'userId' : UserId,
  'date' : Timestamp,
  'name' : string,
  'time' : Timestamp,
  'agentId' : [] | [bigint],
  'projectId' : bigint,
  'phone' : string,
  'houseType' : [] | [string],
  'houseId' : [] | [bigint],
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface Coordinates { 'lat' : number, 'lng' : number }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Favorite {
  'projects' : Array<bigint>,
  'userId' : UserId,
  'agents' : Array<bigint>,
  'savedPosts' : Array<bigint>,
  'houseTypes' : Array<string>,
  'houses' : Array<bigint>,
}
export interface House {
  'id' : bigint,
  'status' : HouseStatus,
  'bedrooms' : bigint,
  'video' : [] | [string],
  'floorPlan' : [] | [string],
  'projectId' : bigint,
  'usableArea' : bigint,
  'bathrooms' : bigint,
  'price' : bigint,
  'houseType' : string,
  'parking' : bigint,
  'gallery' : Array<string>,
}
export type HouseStatus = { 'underConstruction' : null } |
  { 'readyToMove' : null };
export interface Location {
  'province' : string,
  'district' : string,
  'subDistrict' : string,
}
export interface Notification {
  'id' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'read' : boolean,
  'message' : string,
}
export interface Post {
  'id' : bigint,
  'likeCount' : bigint,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'agentId' : [] | [bigint],
  'interestedCount' : bigint,
  'shareCount' : bigint,
  'projectId' : [] | [bigint],
  'commentCount' : bigint,
  'image' : [] | [string],
  'price' : [] | [bigint],
  'saveCount' : bigint,
  'location' : [] | [Location],
}
export interface Project {
  'id' : bigint,
  'promotions' : Array<string>,
  'startingPrice' : bigint,
  'unitStatus' : UnitStatus,
  'reviewRating' : number,
  'video' : [] | [string],
  'name' : string,
  'unitCount' : bigint,
  'createdAt' : Timestamp,
  'houseTypes' : Array<string>,
  'projectStatus' : ProjectStatus,
  'location' : Location,
  'verificationStatus' : VerificationStatus,
  'coordinates' : Coordinates,
  'images' : Array<string>,
}
export interface ProjectFilter {
  'province' : [] | [string],
  'newProject' : [] | [boolean],
  'bedrooms' : [] | [bigint],
  'name' : [] | [string],
  'maxPrice' : [] | [bigint],
  'district' : [] | [string],
  'promotion' : [] | [boolean],
  'usableArea' : [] | [bigint],
  'minPrice' : [] | [bigint],
  'houseType' : [] | [string],
  'readyToMove' : [] | [boolean],
  'location' : [] | [string],
}
export type ProjectStatus = { 'new' : null } |
  { 'completed' : null } |
  { 'ongoing' : null };
export interface RatingCategory {
  'service' : bigint,
  'trust' : bigint,
  'info' : bigint,
  'followUp' : bigint,
  'speed' : bigint,
  'politeness' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Review {
  'id' : bigint,
  'categories' : RatingCategory,
  'createdAt' : Timestamp,
  'agentId' : bigint,
  'reviewerId' : UserId,
  'comment' : string,
  'rating' : bigint,
  'reported' : boolean,
}
export type Timestamp = bigint;
export type UnitStatus = { 'sold' : null } |
  { 'reserved' : null } |
  { 'available' : null };
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type VerificationStatus = { 'verified' : null } |
  { 'none' : null } |
  { 'official' : null };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addAgent' : ActorMethod<[Agent], bigint>,
  'addFavoriteAgent' : ActorMethod<[bigint], undefined>,
  'addFavoriteHouse' : ActorMethod<[bigint], undefined>,
  'addFavoriteHouseType' : ActorMethod<[string], undefined>,
  'addFavoriteProject' : ActorMethod<[bigint], undefined>,
  'addHouse' : ActorMethod<[House], bigint>,
  'addPost' : ActorMethod<[Post], bigint>,
  'addProject' : ActorMethod<[Project], bigint>,
  'addReview' : ActorMethod<[Review], bigint>,
  'addSavedPost' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[Appointment], bigint>,
  'cancelAppointment' : ActorMethod<[bigint], undefined>,
  'commentPost' : ActorMethod<[bigint], undefined>,
  'confirmAppointment' : ActorMethod<[bigint], undefined>,
  'deleteAgent' : ActorMethod<[bigint], undefined>,
  'deleteHouse' : ActorMethod<[bigint], undefined>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getAdminMetrics' : ActorMethod<[], AdminMetrics>,
  'getAgent' : ActorMethod<[bigint], [] | [Agent]>,
  'getApiDoc' : ActorMethod<[], string>,
  'getAppointment' : ActorMethod<[bigint], [] | [Appointment]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavorites' : ActorMethod<[], Favorite>,
  'getHouse' : ActorMethod<[bigint], [] | [House]>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'listAgents' : ActorMethod<[], Array<Agent>>,
  'listAppointments' : ActorMethod<[], Array<Appointment>>,
  'listHouses' : ActorMethod<[[] | [bigint]], Array<House>>,
  'listNotifications' : ActorMethod<[], Array<Notification>>,
  'listPosts' : ActorMethod<[], Array<Post>>,
  'listProjects' : ActorMethod<[ProjectFilter], Array<Project>>,
  'listReviews' : ActorMethod<[bigint], Array<Review>>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'removeFavoriteAgent' : ActorMethod<[bigint], undefined>,
  'removeFavoriteHouse' : ActorMethod<[bigint], undefined>,
  'removeFavoriteHouseType' : ActorMethod<[string], undefined>,
  'removeFavoriteProject' : ActorMethod<[bigint], undefined>,
  'removeSavedPost' : ActorMethod<[bigint], undefined>,
  'reportReview' : ActorMethod<[bigint], undefined>,
  'savePost' : ActorMethod<[bigint], undefined>,
  'schema' : ActorMethod<[], string>,
  'sharePost' : ActorMethod<[bigint], undefined>,
  'smartSearch' : ActorMethod<[string], Array<Project>>,
  'updateAgent' : ActorMethod<[Agent], undefined>,
  'updateHouse' : ActorMethod<[House], undefined>,
  'updateProject' : ActorMethod<[Project], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];