/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Location {
    province: string;
    district: string;
    subDistrict: string;
}
export type Timestamp = bigint;
export interface Coordinates {
    lat: number;
    lng: number;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface RatingCategory {
    service: bigint;
    trust: bigint;
    info: bigint;
    followUp: bigint;
    speed: bigint;
    politeness: bigint;
}
export interface Favorite {
    projects: Array<bigint>;
    userId: UserId;
    agents: Array<bigint>;
    savedPosts: Array<bigint>;
    houseTypes: Array<string>;
    houses: Array<bigint>;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Agent {
    id: bigint;
    portfolio: Array<string>;
    serviceArea: string;
    ratingCategories: RatingCategory;
    listedHomes: Array<bigint>;
    verified: boolean;
    userId: UserId;
    managedProjects: Array<bigint>;
    name: string;
    agentCode: string;
    experience: bigint;
    customerCount: bigint;
    rating: number;
    photo?: string;
    reviewCount: bigint;
}
export type UserId = Principal;
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface AdminMetrics {
    members: bigint;
    projects: bigint;
    agents: bigint;
    leads: bigint;
    liveViewers: bigint;
    appointments: bigint;
    conversions: bigint;
    posts: bigint;
    houses: bigint;
    customers: bigint;
}
export interface Post {
    id: bigint;
    likeCount: bigint;
    authorId: UserId;
    createdAt: Timestamp;
    agentId?: bigint;
    interestedCount: bigint;
    shareCount: bigint;
    projectId?: bigint;
    commentCount: bigint;
    image?: string;
    price?: bigint;
    saveCount: bigint;
    location?: Location;
}
export interface ProjectFilter {
    province?: string;
    newProject?: boolean;
    bedrooms?: bigint;
    name?: string;
    maxPrice?: bigint;
    district?: string;
    promotion?: boolean;
    usableArea?: bigint;
    minPrice?: bigint;
    houseType?: string;
    readyToMove?: boolean;
    location?: string;
}
export interface Notification {
    id: bigint;
    userId: UserId;
    createdAt: Timestamp;
    read: boolean;
    message: string;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface House {
    id: bigint;
    status: HouseStatus;
    bedrooms: bigint;
    video?: string;
    floorPlan?: string;
    projectId: bigint;
    usableArea: bigint;
    bathrooms: bigint;
    price: bigint;
    houseType: string;
    parking: bigint;
    gallery: Array<string>;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface Project {
    id: bigint;
    promotions: Array<string>;
    startingPrice: bigint;
    unitStatus: UnitStatus;
    reviewRating: number;
    video?: string;
    name: string;
    unitCount: bigint;
    createdAt: Timestamp;
    houseTypes: Array<string>;
    projectStatus: ProjectStatus;
    location: Location;
    verificationStatus: VerificationStatus;
    coordinates: Coordinates;
    images: Array<string>;
}
export interface Review {
    id: bigint;
    categories: RatingCategory;
    createdAt: Timestamp;
    agentId: bigint;
    reviewerId: UserId;
    comment: string;
    rating: bigint;
    reported: boolean;
}
export interface Appointment {
    id: bigint;
    status: AppointmentStatus;
    visitors: bigint;
    userId: UserId;
    date: Timestamp;
    name: string;
    time: Timestamp;
    agentId?: bigint;
    projectId: bigint;
    phone: string;
    houseType?: string;
    houseId?: bigint;
}
export enum AppointmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum HouseStatus {
    underConstruction = "underConstruction",
    readyToMove = "readyToMove"
}
export enum ProjectStatus {
    new_ = "new",
    completed = "completed",
    ongoing = "ongoing"
}
export enum UnitStatus {
    sold = "sold",
    reserved = "reserved",
    available = "available"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VerificationStatus {
    verified = "verified",
    none = "none",
    official = "official"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addAgent(agent: Agent): Promise<bigint>;
    addFavoriteAgent(agentId: bigint): Promise<void>;
    addFavoriteHouse(houseId: bigint): Promise<void>;
    addFavoriteHouseType(houseType: string): Promise<void>;
    addFavoriteProject(projectId: bigint): Promise<void>;
    addHouse(house: House): Promise<bigint>;
    addPost(post: Post): Promise<bigint>;
    addProject(project: Project): Promise<bigint>;
    addReview(review: Review): Promise<bigint>;
    addSavedPost(postId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookAppointment(appointment: Appointment): Promise<bigint>;
    cancelAppointment(id: bigint): Promise<void>;
    commentPost(id: bigint): Promise<void>;
    confirmAppointment(id: bigint): Promise<void>;
    deleteAgent(id: bigint): Promise<void>;
    deleteHouse(id: bigint): Promise<void>;
    deleteProject(id: bigint): Promise<void>;
    execute(qJson: string): Promise<Result>;
    getAdminMetrics(): Promise<AdminMetrics>;
    getAgent(id: bigint): Promise<Agent | null>;
    getApiDoc(): Promise<string>;
    getAppointment(id: bigint): Promise<Appointment | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFavorites(): Promise<Favorite>;
    getHouse(id: bigint): Promise<House | null>;
    getPost(id: bigint): Promise<Post | null>;
    getProject(id: bigint): Promise<Project | null>;
    isCallerAdmin(): Promise<boolean>;
    likePost(id: bigint): Promise<void>;
    listAgents(): Promise<Array<Agent>>;
    listAppointments(): Promise<Array<Appointment>>;
    listHouses(projectId: bigint | null): Promise<Array<House>>;
    listNotifications(): Promise<Array<Notification>>;
    listPosts(): Promise<Array<Post>>;
    listProjects(filter: ProjectFilter): Promise<Array<Project>>;
    listReviews(agentId: bigint): Promise<Array<Review>>;
    markNotificationRead(id: bigint): Promise<void>;
    removeFavoriteAgent(agentId: bigint): Promise<void>;
    removeFavoriteHouse(houseId: bigint): Promise<void>;
    removeFavoriteHouseType(houseType: string): Promise<void>;
    removeFavoriteProject(projectId: bigint): Promise<void>;
    removeSavedPost(postId: bigint): Promise<void>;
    reportReview(id: bigint): Promise<void>;
    savePost(id: bigint): Promise<void>;
    schema(): Promise<string>;
    sharePost(id: bigint): Promise<void>;
    smartSearch(q: string): Promise<Array<Project>>;
    updateAgent(agent: Agent): Promise<void>;
    updateHouse(house: House): Promise<void>;
    updateProject(project: Project): Promise<void>;
}
import type { Agent as _Agent, Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, Cell as _Cell, Coordinates as _Coordinates, Error as _Error, House as _House, HouseStatus as _HouseStatus, Location as _Location, Post as _Post, Project as _Project, ProjectFilter as _ProjectFilter, ProjectStatus as _ProjectStatus, RatingCategory as _RatingCategory, Result as _Result, Result__1 as _Result__1, Timestamp as _Timestamp, UnitStatus as _UnitStatus, UserId as _UserId, UserRole as _UserRole, Value as _Value, VerificationStatus as _VerificationStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addAgent(arg0: Agent): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAgent(to_candid_Agent_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAgent(to_candid_Agent_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addFavoriteAgent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavoriteAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavoriteAgent(arg0);
            return result;
        }
    }
    async addFavoriteHouse(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavoriteHouse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavoriteHouse(arg0);
            return result;
        }
    }
    async addFavoriteHouseType(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavoriteHouseType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavoriteHouseType(arg0);
            return result;
        }
    }
    async addFavoriteProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavoriteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavoriteProject(arg0);
            return result;
        }
    }
    async addHouse(arg0: House): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHouse(to_candid_House_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHouse(to_candid_House_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPost(arg0: Post): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPost(to_candid_Post_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPost(to_candid_Post_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProject(arg0: Project): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(to_candid_Project_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(to_candid_Project_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addReview(arg0: Review): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0);
            return result;
        }
    }
    async addSavedPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSavedPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSavedPost(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookAppointment(arg0: Appointment): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(to_candid_Appointment_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(to_candid_Appointment_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async cancelAppointment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return result;
        }
    }
    async commentPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.commentPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.commentPost(arg0);
            return result;
        }
    }
    async confirmAppointment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmAppointment(arg0);
            return result;
        }
    }
    async deleteAgent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAgent(arg0);
            return result;
        }
    }
    async deleteHouse(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHouse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHouse(arg0);
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminMetrics(): Promise<AdminMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminMetrics();
            return result;
        }
    }
    async getAgent(arg0: bigint): Promise<Agent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgent(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgent(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getAppointment(arg0: bigint): Promise<Appointment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFavorites(): Promise<Favorite> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites();
            return result;
        }
    }
    async getHouse(arg0: bigint): Promise<House | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHouse(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHouse(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: bigint): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async likePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async listAgents(): Promise<Array<Agent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAgents();
                return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAgents();
            return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAppointments();
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAppointments();
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async listHouses(arg0: bigint | null): Promise<Array<House>> {
        if (this.processError) {
            try {
                const result = await this.actor.listHouses(to_candid_opt_n67(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listHouses(to_candid_opt_n67(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotifications();
            return result;
        }
    }
    async listPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPosts();
                return from_candid_vec_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPosts();
            return from_candid_vec_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjects(arg0: ProjectFilter): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects(to_candid_ProjectFilter_n70(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects(to_candid_ProjectFilter_n70(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async listReviews(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReviews(arg0);
            return result;
        }
    }
    async markNotificationRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async removeFavoriteAgent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavoriteAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavoriteAgent(arg0);
            return result;
        }
    }
    async removeFavoriteHouse(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavoriteHouse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavoriteHouse(arg0);
            return result;
        }
    }
    async removeFavoriteHouseType(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavoriteHouseType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavoriteHouseType(arg0);
            return result;
        }
    }
    async removeFavoriteProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavoriteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavoriteProject(arg0);
            return result;
        }
    }
    async removeSavedPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSavedPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSavedPost(arg0);
            return result;
        }
    }
    async reportReview(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportReview(arg0);
            return result;
        }
    }
    async savePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePost(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async sharePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sharePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sharePost(arg0);
            return result;
        }
    }
    async smartSearch(arg0: string): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.smartSearch(arg0);
                return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.smartSearch(arg0);
            return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAgent(arg0: Agent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAgent(to_candid_Agent_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAgent(to_candid_Agent_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateHouse(arg0: House): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHouse(to_candid_House_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHouse(to_candid_House_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProject(arg0: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(to_candid_Project_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(to_candid_Project_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Agent_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Agent): Agent {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_AppointmentStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_HouseStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HouseStatus): HouseStatus {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_House_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _House): House {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Post_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UnitStatus_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UnitStatus): UnitStatus {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Agent]): Agent | null {
    return value.length === 0 ? null : from_candid_Agent_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Appointment]): Appointment | null {
    return value.length === 0 ? null : from_candid_Appointment_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_House]): House | null {
    return value.length === 0 ? null : from_candid_House_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Post | null {
    return value.length === 0 ? null : from_candid_Post_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n57(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n29(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n33(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    portfolio: Array<string>;
    serviceArea: string;
    ratingCategories: _RatingCategory;
    listedHomes: Array<bigint>;
    verified: boolean;
    userId: _UserId;
    managedProjects: Array<bigint>;
    name: string;
    agentCode: string;
    experience: bigint;
    customerCount: bigint;
    rating: number;
    photo: [] | [string];
    reviewCount: bigint;
}): {
    id: bigint;
    portfolio: Array<string>;
    serviceArea: string;
    ratingCategories: RatingCategory;
    listedHomes: Array<bigint>;
    verified: boolean;
    userId: UserId;
    managedProjects: Array<bigint>;
    name: string;
    agentCode: string;
    experience: bigint;
    customerCount: bigint;
    rating: number;
    photo?: string;
    reviewCount: bigint;
} {
    return {
        id: value.id,
        portfolio: value.portfolio,
        serviceArea: value.serviceArea,
        ratingCategories: value.ratingCategories,
        listedHomes: value.listedHomes,
        verified: value.verified,
        userId: value.userId,
        managedProjects: value.managedProjects,
        name: value.name,
        agentCode: value.agentCode,
        experience: value.experience,
        customerCount: value.customerCount,
        rating: value.rating,
        photo: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.photo)),
        reviewCount: value.reviewCount
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AppointmentStatus;
    visitors: bigint;
    userId: _UserId;
    date: _Timestamp;
    name: string;
    time: _Timestamp;
    agentId: [] | [bigint];
    projectId: bigint;
    phone: string;
    houseType: [] | [string];
    houseId: [] | [bigint];
}): {
    id: bigint;
    status: AppointmentStatus;
    visitors: bigint;
    userId: UserId;
    date: Timestamp;
    name: string;
    time: Timestamp;
    agentId?: bigint;
    projectId: bigint;
    phone: string;
    houseType?: string;
    houseId?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n42(_uploadFile, _downloadFile, value.status),
        visitors: value.visitors,
        userId: value.userId,
        date: value.date,
        name: value.name,
        time: value.time,
        agentId: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.agentId)),
        projectId: value.projectId,
        phone: value.phone,
        houseType: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.houseType)),
        houseId: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.houseId))
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _HouseStatus;
    bedrooms: bigint;
    video: [] | [string];
    floorPlan: [] | [string];
    projectId: bigint;
    usableArea: bigint;
    bathrooms: bigint;
    price: bigint;
    houseType: string;
    parking: bigint;
    gallery: Array<string>;
}): {
    id: bigint;
    status: HouseStatus;
    bedrooms: bigint;
    video?: string;
    floorPlan?: string;
    projectId: bigint;
    usableArea: bigint;
    bathrooms: bigint;
    price: bigint;
    houseType: string;
    parking: bigint;
    gallery: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_HouseStatus_n50(_uploadFile, _downloadFile, value.status),
        bedrooms: value.bedrooms,
        video: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.video)),
        floorPlan: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.floorPlan)),
        projectId: value.projectId,
        usableArea: value.usableArea,
        bathrooms: value.bathrooms,
        price: value.price,
        houseType: value.houseType,
        parking: value.parking,
        gallery: value.gallery
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    likeCount: bigint;
    authorId: _UserId;
    createdAt: _Timestamp;
    agentId: [] | [bigint];
    interestedCount: bigint;
    shareCount: bigint;
    projectId: [] | [bigint];
    commentCount: bigint;
    image: [] | [string];
    price: [] | [bigint];
    saveCount: bigint;
    location: [] | [_Location];
}): {
    id: bigint;
    likeCount: bigint;
    authorId: UserId;
    createdAt: Timestamp;
    agentId?: bigint;
    interestedCount: bigint;
    shareCount: bigint;
    projectId?: bigint;
    commentCount: bigint;
    image?: string;
    price?: bigint;
    saveCount: bigint;
    location?: Location;
} {
    return {
        id: value.id,
        likeCount: value.likeCount,
        authorId: value.authorId,
        createdAt: value.createdAt,
        agentId: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.agentId)),
        interestedCount: value.interestedCount,
        shareCount: value.shareCount,
        projectId: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.projectId)),
        commentCount: value.commentCount,
        image: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.image)),
        price: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.price)),
        saveCount: value.saveCount,
        location: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    promotions: Array<string>;
    startingPrice: bigint;
    unitStatus: _UnitStatus;
    reviewRating: number;
    video: [] | [string];
    name: string;
    unitCount: bigint;
    createdAt: _Timestamp;
    houseTypes: Array<string>;
    projectStatus: _ProjectStatus;
    location: _Location;
    verificationStatus: _VerificationStatus;
    coordinates: _Coordinates;
    images: Array<string>;
}): {
    id: bigint;
    promotions: Array<string>;
    startingPrice: bigint;
    unitStatus: UnitStatus;
    reviewRating: number;
    video?: string;
    name: string;
    unitCount: bigint;
    createdAt: Timestamp;
    houseTypes: Array<string>;
    projectStatus: ProjectStatus;
    location: Location;
    verificationStatus: VerificationStatus;
    coordinates: Coordinates;
    images: Array<string>;
} {
    return {
        id: value.id,
        promotions: value.promotions,
        startingPrice: value.startingPrice,
        unitStatus: from_candid_UnitStatus_n59(_uploadFile, _downloadFile, value.unitStatus),
        reviewRating: value.reviewRating,
        video: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.video)),
        name: value.name,
        unitCount: value.unitCount,
        createdAt: value.createdAt,
        houseTypes: value.houseTypes,
        projectStatus: from_candid_ProjectStatus_n61(_uploadFile, _downloadFile, value.projectStatus),
        location: value.location,
        verificationStatus: from_candid_VerificationStatus_n63(_uploadFile, _downloadFile, value.verificationStatus),
        coordinates: value.coordinates,
        images: value.images
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "completed" in value ? AppointmentStatus.completed : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    underConstruction: null;
} | {
    readyToMove: null;
}): HouseStatus {
    return "underConstruction" in value ? HouseStatus.underConstruction : "readyToMove" in value ? HouseStatus.readyToMove : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sold: null;
} | {
    reserved: null;
} | {
    available: null;
}): UnitStatus {
    return "sold" in value ? UnitStatus.sold : "reserved" in value ? UnitStatus.reserved : "available" in value ? UnitStatus.available : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    completed: null;
} | {
    ongoing: null;
}): ProjectStatus {
    return "new" in value ? ProjectStatus.new : "completed" in value ? ProjectStatus.completed : "ongoing" in value ? ProjectStatus.ongoing : value;
}
function from_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    none: null;
} | {
    official: null;
}): VerificationStatus {
    return "verified" in value ? VerificationStatus.verified : "none" in value ? VerificationStatus.none : "official" in value ? VerificationStatus.official : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Agent>): Array<Agent> {
    return value.map((x)=>from_candid_Agent_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_House>): Array<House> {
    return value.map((x)=>from_candid_House_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n53(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n57(_uploadFile, _downloadFile, x));
}
function to_candid_Agent_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Agent): _Agent {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_AppointmentStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_Appointment_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Appointment): _Appointment {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_HouseStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HouseStatus): _HouseStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_House_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: House): _House {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Post_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Post): _Post {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectFilter_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectFilter): _ProjectFilter {
    return to_candid_record_n71(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Project_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): _Project {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UnitStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UnitStatus): _UnitStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_VerificationStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): _VerificationStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    likeCount: bigint;
    authorId: UserId;
    createdAt: Timestamp;
    agentId?: bigint;
    interestedCount: bigint;
    shareCount: bigint;
    projectId?: bigint;
    commentCount: bigint;
    image?: string;
    price?: bigint;
    saveCount: bigint;
    location?: Location;
}): {
    id: bigint;
    likeCount: bigint;
    authorId: _UserId;
    createdAt: _Timestamp;
    agentId: [] | [bigint];
    interestedCount: bigint;
    shareCount: bigint;
    projectId: [] | [bigint];
    commentCount: bigint;
    image: [] | [string];
    price: [] | [bigint];
    saveCount: bigint;
    location: [] | [_Location];
} {
    return {
        id: value.id,
        likeCount: value.likeCount,
        authorId: value.authorId,
        createdAt: value.createdAt,
        agentId: value.agentId ? candid_some(value.agentId) : candid_none(),
        interestedCount: value.interestedCount,
        shareCount: value.shareCount,
        projectId: value.projectId ? candid_some(value.projectId) : candid_none(),
        commentCount: value.commentCount,
        image: value.image ? candid_some(value.image) : candid_none(),
        price: value.price ? candid_some(value.price) : candid_none(),
        saveCount: value.saveCount,
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    promotions: Array<string>;
    startingPrice: bigint;
    unitStatus: UnitStatus;
    reviewRating: number;
    video?: string;
    name: string;
    unitCount: bigint;
    createdAt: Timestamp;
    houseTypes: Array<string>;
    projectStatus: ProjectStatus;
    location: Location;
    verificationStatus: VerificationStatus;
    coordinates: Coordinates;
    images: Array<string>;
}): {
    id: bigint;
    promotions: Array<string>;
    startingPrice: bigint;
    unitStatus: _UnitStatus;
    reviewRating: number;
    video: [] | [string];
    name: string;
    unitCount: bigint;
    createdAt: _Timestamp;
    houseTypes: Array<string>;
    projectStatus: _ProjectStatus;
    location: _Location;
    verificationStatus: _VerificationStatus;
    coordinates: _Coordinates;
    images: Array<string>;
} {
    return {
        id: value.id,
        promotions: value.promotions,
        startingPrice: value.startingPrice,
        unitStatus: to_candid_UnitStatus_n15(_uploadFile, _downloadFile, value.unitStatus),
        reviewRating: value.reviewRating,
        video: value.video ? candid_some(value.video) : candid_none(),
        name: value.name,
        unitCount: value.unitCount,
        createdAt: value.createdAt,
        houseTypes: value.houseTypes,
        projectStatus: to_candid_ProjectStatus_n17(_uploadFile, _downloadFile, value.projectStatus),
        location: value.location,
        verificationStatus: to_candid_VerificationStatus_n19(_uploadFile, _downloadFile, value.verificationStatus),
        coordinates: value.coordinates,
        images: value.images
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: AppointmentStatus;
    visitors: bigint;
    userId: UserId;
    date: Timestamp;
    name: string;
    time: Timestamp;
    agentId?: bigint;
    projectId: bigint;
    phone: string;
    houseType?: string;
    houseId?: bigint;
}): {
    id: bigint;
    status: _AppointmentStatus;
    visitors: bigint;
    userId: _UserId;
    date: _Timestamp;
    name: string;
    time: _Timestamp;
    agentId: [] | [bigint];
    projectId: bigint;
    phone: string;
    houseType: [] | [string];
    houseId: [] | [bigint];
} {
    return {
        id: value.id,
        status: to_candid_AppointmentStatus_n25(_uploadFile, _downloadFile, value.status),
        visitors: value.visitors,
        userId: value.userId,
        date: value.date,
        name: value.name,
        time: value.time,
        agentId: value.agentId ? candid_some(value.agentId) : candid_none(),
        projectId: value.projectId,
        phone: value.phone,
        houseType: value.houseType ? candid_some(value.houseType) : candid_none(),
        houseId: value.houseId ? candid_some(value.houseId) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    portfolio: Array<string>;
    serviceArea: string;
    ratingCategories: RatingCategory;
    listedHomes: Array<bigint>;
    verified: boolean;
    userId: UserId;
    managedProjects: Array<bigint>;
    name: string;
    agentCode: string;
    experience: bigint;
    customerCount: bigint;
    rating: number;
    photo?: string;
    reviewCount: bigint;
}): {
    id: bigint;
    portfolio: Array<string>;
    serviceArea: string;
    ratingCategories: _RatingCategory;
    listedHomes: Array<bigint>;
    verified: boolean;
    userId: _UserId;
    managedProjects: Array<bigint>;
    name: string;
    agentCode: string;
    experience: bigint;
    customerCount: bigint;
    rating: number;
    photo: [] | [string];
    reviewCount: bigint;
} {
    return {
        id: value.id,
        portfolio: value.portfolio,
        serviceArea: value.serviceArea,
        ratingCategories: value.ratingCategories,
        listedHomes: value.listedHomes,
        verified: value.verified,
        userId: value.userId,
        managedProjects: value.managedProjects,
        name: value.name,
        agentCode: value.agentCode,
        experience: value.experience,
        customerCount: value.customerCount,
        rating: value.rating,
        photo: value.photo ? candid_some(value.photo) : candid_none(),
        reviewCount: value.reviewCount
    };
}
function to_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    province?: string;
    newProject?: boolean;
    bedrooms?: bigint;
    name?: string;
    maxPrice?: bigint;
    district?: string;
    promotion?: boolean;
    usableArea?: bigint;
    minPrice?: bigint;
    houseType?: string;
    readyToMove?: boolean;
    location?: string;
}): {
    province: [] | [string];
    newProject: [] | [boolean];
    bedrooms: [] | [bigint];
    name: [] | [string];
    maxPrice: [] | [bigint];
    district: [] | [string];
    promotion: [] | [boolean];
    usableArea: [] | [bigint];
    minPrice: [] | [bigint];
    houseType: [] | [string];
    readyToMove: [] | [boolean];
    location: [] | [string];
} {
    return {
        province: value.province ? candid_some(value.province) : candid_none(),
        newProject: value.newProject ? candid_some(value.newProject) : candid_none(),
        bedrooms: value.bedrooms ? candid_some(value.bedrooms) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        district: value.district ? candid_some(value.district) : candid_none(),
        promotion: value.promotion ? candid_some(value.promotion) : candid_none(),
        usableArea: value.usableArea ? candid_some(value.usableArea) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none(),
        houseType: value.houseType ? candid_some(value.houseType) : candid_none(),
        readyToMove: value.readyToMove ? candid_some(value.readyToMove) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: HouseStatus;
    bedrooms: bigint;
    video?: string;
    floorPlan?: string;
    projectId: bigint;
    usableArea: bigint;
    bathrooms: bigint;
    price: bigint;
    houseType: string;
    parking: bigint;
    gallery: Array<string>;
}): {
    id: bigint;
    status: _HouseStatus;
    bedrooms: bigint;
    video: [] | [string];
    floorPlan: [] | [string];
    projectId: bigint;
    usableArea: bigint;
    bathrooms: bigint;
    price: bigint;
    houseType: string;
    parking: bigint;
    gallery: Array<string>;
} {
    return {
        id: value.id,
        status: to_candid_HouseStatus_n9(_uploadFile, _downloadFile, value.status),
        bedrooms: value.bedrooms,
        video: value.video ? candid_some(value.video) : candid_none(),
        floorPlan: value.floorPlan ? candid_some(value.floorPlan) : candid_none(),
        projectId: value.projectId,
        usableArea: value.usableArea,
        bathrooms: value.bathrooms,
        price: value.price,
        houseType: value.houseType,
        parking: value.parking,
        gallery: value.gallery
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HouseStatus): {
    underConstruction: null;
} | {
    readyToMove: null;
} {
    return value == HouseStatus.underConstruction ? {
        underConstruction: null
    } : value == HouseStatus.readyToMove ? {
        readyToMove: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UnitStatus): {
    sold: null;
} | {
    reserved: null;
} | {
    available: null;
} {
    return value == UnitStatus.sold ? {
        sold: null
    } : value == UnitStatus.reserved ? {
        reserved: null
    } : value == UnitStatus.available ? {
        available: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    new: null;
} | {
    completed: null;
} | {
    ongoing: null;
} {
    return value == ProjectStatus.new ? {
        new_: null
    } : value == ProjectStatus.completed ? {
        completed: null
    } : value == ProjectStatus.ongoing ? {
        ongoing: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): {
    verified: null;
} | {
    none: null;
} | {
    official: null;
} {
    return value == VerificationStatus.verified ? {
        verified: null
    } : value == VerificationStatus.none ? {
        none: null
    } : value == VerificationStatus.official ? {
        official: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.pending ? {
        pending: null
    } : value == AppointmentStatus.completed ? {
        completed: null
    } : value == AppointmentStatus.confirmed ? {
        confirmed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
